// SPDX-FileCopyrightText: © 2026 Fabrizio Salmi
// SPDX-License-Identifier: AGPL-3.0-only

// Package runbook renders the human-facing migration document: the assessment
// summary, the generated artifacts, the ordered cutover steps (as flareover
// commands), and the rollback. It is the paper trail a migration deserves: every
// MANUAL item is listed so nothing is quietly assumed, and the cutover is a
// gated, reversible sequence, not a leap.
package runbook

import (
	"fmt"
	"sort"
	"strings"

	"github.com/fabriziosalmi/flareover/internal/ir"
	"github.com/fabriziosalmi/flareover/internal/report"
)

// Generate renders MIGRATION.md for a zone from its assessment, plan, and the
// artifact paths that were written.
func Generate(rep report.Report, plan ir.Plan, artifacts []string) []byte {
	var b strings.Builder
	c := rep.Counts()

	fmt.Fprintf(&b, "# Migration report: `%s`\n\n", rep.Zone)
	total := len(rep.Findings)
	pct := 0
	if total > 0 {
		pct = c[report.Auto] * 100 / total
	}
	fmt.Fprintf(&b, "Generated by flareover. **%d** Cloudflare elements found: "+
		"**%d migrated 1:1** (AUTO), **%d** need one decision (ASK), **%d** to handle by hand (MANUAL). "+
		"**%d%% mapped automatically**.\n\n", total, c[report.Auto], c[report.Ask], c[report.Manual], pct)

	// The heart of the report: everything found on Cloudflare, and exactly what it
	// became. AUTO rows are the faithful 1:1 migrations; ASK/MANUAL are flagged so
	// nothing is silently assumed.
	b.WriteString("## What we found on Cloudflare, and what it became\n\n")
	b.WriteString("| Status | Cloudflare element | → Target | What it became / why not |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, f := range rep.Sorted() {
		tgt := f.Target
		if tgt == "" {
			tgt = "n/a"
		}
		detail := f.Rationale
		if f.Question != nil {
			detail = f.Question.Prompt
		}
		fmt.Fprintf(&b, "| %s | %s `%s` | %s | %s |\n",
			statusBadge(f.Verdict), f.Kind, f.Name, tgt, escapePipes(detail))
	}
	b.WriteString("\n_✅ migrated 1:1 · ⚠️ one decision needed · ✋ handle by hand (never guessed)._\n\n")

	// MANUAL: the things flareover will not touch. Listed first, on purpose.
	var manual, ask []report.Finding
	for _, f := range rep.Sorted() {
		switch f.Verdict {
		case report.Manual:
			manual = append(manual, f)
		case report.Ask:
			ask = append(ask, f)
		}
	}
	if len(manual) > 0 {
		b.WriteString("## Handle by hand (MANUAL)\n\nThese have no faithful automatic mapping and are **not** generated. Recreate them yourself:\n\n")
		for _, f := range manual {
			fmt.Fprintf(&b, "- **%s** `%s`: %s\n", f.Kind, f.Name, f.Rationale)
		}
		b.WriteString("\n")
	}
	if len(ask) > 0 {
		b.WriteString("## Decisions required (ASK)\n\nResolve these into `decisions.lock` (`flareover resolve`); each is one bounded choice:\n\n")
		for _, f := range ask {
			def := ""
			if f.Question != nil && f.Question.Default != "" {
				def = fmt.Sprintf(" _(default %s)_", f.Question.Default)
			}
			q := f.Rationale
			if f.Question != nil {
				q = f.Question.Prompt
			}
			fmt.Fprintf(&b, "- **%s** `%s`: %s%s\n", f.Kind, f.Name, q, def)
		}
		b.WriteString("\n")
	}

	// Generated artifacts.
	if len(artifacts) > 0 {
		b.WriteString("## Generated artifacts\n\n")
		sorted := append([]string(nil), artifacts...)
		sort.Strings(sorted)
		for _, a := range sorted {
			fmt.Fprintf(&b, "- `%s`\n", a)
		}
		b.WriteString("\n")
	}

	// The plan at a glance.
	fmt.Fprintf(&b, "## Target at a glance\n\n%d DNS records · %d sites · %d custom WAF rules%s.\n\n",
		len(plan.DNS.Records), len(plan.Sites), len(plan.WAF.CustomRules), dnssecNote(plan))

	// Cutover runbook: the ordered, gated, reversible sequence.
	b.WriteString("## Cutover runbook\n\n")
	b.WriteString("1. **Lower TTLs** on the records to flip (e.g. 60s) and let the old TTL expire.\n")
	b.WriteString("2. **Provision** the target: `flareover provision --snapshot s.json --decisions decisions.lock --pdns-url … --certmate-url …`\n")
	b.WriteString("3. **Deploy** the generated Caddy/caddy-waf config to the edge and start it.\n")
	b.WriteString("4. **Gate**: `flareover present --snapshot s.json --decisions decisions.lock --after-addr <edge-ip>:443`. Cutover only if it prints **GATE: PASS**.\n")
	b.WriteString("5. **Flip DNS** to the new edge (your explicit, write-scoped step).\n")
	b.WriteString("6. **Watch**: `flareover guard --url https://<zone>/ --on-unhealthy \"<rollback command>\"`. Auto-rollback if health degrades.\n\n")

	b.WriteString("## Rollback\n\n")
	b.WriteString("Repoint the flipped records back to the source. Because DNS is the only thing that changed and TTLs are low, rollback is a single DNS write and takes effect in seconds.\n")

	return []byte(b.String())
}

// statusBadge maps a verdict to a scannable icon + label for the report table.
func statusBadge(v report.Verdict) string {
	switch v {
	case report.Auto:
		return "✅ AUTO"
	case report.Ask:
		return "⚠️ ASK"
	case report.Manual:
		return "✋ MANUAL"
	default:
		return string(v)
	}
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

func dnssecNote(p ir.Plan) string {
	if p.DNS.DNSSEC {
		return " · DNSSEC (publish the DS at your registrar)"
	}
	return ""
}
